config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:edit, :update]
  resources :events, only: [:create]

  root "welcome#home"
  get "/login", to: "sessions#create"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#dashboard"
  get "/scheduler", to: "users#scheduler"
  get '/auth/meetup/callback', to: 'sessions#create'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  def self.create_events_by_params(events, current_user)
    events.each do |event|
      new_event = Event.create(user_id: current_user.id,
                               utc_offset: event["utc_offset"],
                               country: event["venue"]["country"],
                               city: event["venue"]["city"],
                               state: event["venue"]["state"],
                               distance: event["distance"],
                               name: event["name"],
                               meetup_event_id: event["id"],
                               time: event["time"],
                               group: event["group"]["name"],
                               description: event["description"],
                               status: event["status"])
      new_event.save
      current_user.events << new_event
    end
  end
end

app/models/meetup_auth.rb
class MeetupAuth

  def request_token(code)
    conn = Faraday.new(url: "https://secure.meetup.com/oauth2/access") do |faraday|
      faraday.adapter Faraday.default_adapter
      faraday.request :url_encoded
      faraday.params[:code] = code
      faraday.params[:client_id] = ENV["MEETUP_CONSUMER_KEY"]
      faraday.params[:client_secret] = ENV["MEETUP_CONSUMER_SECRET"]
      faraday.params[:grant_type] = "authorization_code"
      faraday.params[:redirect_uri] = "#{ENV['HOST']}/login"
    end
    JSON.parse(conn.post("https://secure.meetup.com/oauth2/access").body, symbolize_names: true)
  end

  def request_user_info(token)
    conn = Faraday.new(url: "https://api.meetup.com") do |faraday|
      faraday.adapter Faraday.default_adapter
      faraday.params[:key] = ENV["MEETUP_API_KEY"]
      faraday.params[:sign] = "true"
      faraday.params[:access_token] = token
    end
    JSON.parse(conn.get("/members/self").body, symbolize_names: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events

  def self.find_or_create_by_auth(response, user_info)
    user = User.find_or_create_by(meetup_id: user_info[:id])
    user.name = user_info[:name]
    user.status = user_info[:status]
    user.city = user_info[:city]
    user.country = user_info[:country]
    user.state = user_info[:state]
    user.lat = user_info[:lat]
    user.lon = user_info[:lon]
    user.photo = user_info[:photo][:photo_link]
    user.token = response[:access_token]
    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def create
    Event.create_events_by_params(params["_json"], current_user)
    render nothing: true
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def new
  end

  def create
    auth = MeetupAuth.new
    response = auth.request_token(request.GET["code"])
    user_info = auth.request_user_info(response[:access_token])
    user = User.find_or_create_by_auth(response, user_info)
    if user
      session[:user_id] = user.id
      @user = DashboardPresenter.new(current_user, view_context)
      redirect_to dashboard_path
    else
      flash[:error] = "Invalid login information."
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
    if current_user
      @presenter = DashboardPresenter.new(current_user, view_context)
    else
      redirect_to root_path
    end
  end

  def scheduler
    if current_user
      @presenter = SchedulerPresenter.new(current_user, view_context)
    else
      redirect_to root_path
    end
  end

  private

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
xz<nav class="navbar navbar-default navbar-fixed-top">
  <div class="row">
    <%= link_to "EatUp", root_path, class: "navbar-link-left pull-left" %>
    <% if session[:user_id] %>
      <%= link_to "Log out", logout_path, class: "navbar-link-right pull-right" %>
    <% else %>
      <%= link_to "Log in", "https://secure.meetup.com/oauth2/authorize?client_id=#{ENV['MEETUP_CONSUMER_KEY']}&response_type=code&redirect_uri=#{ENV['HOST']}/login&scope=basic+ageless", class: "navbar-link-right pull-right" %>
    <% end %>
    <% if session[:user_id] %>
      <%= link_to "Dashboard", dashboard_path, class: "navbar-link-right pull-right" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EatUp</title>
  <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>
  <%= render partial: "layouts/navbar" %>

  <% flash.each do |type, msg| %>
    <%= content_tag :div, sanitize(message), class: "flash-#{type}" %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/users/dashboard.html.erb
<div class="container-fluid">
  <div class="row dashboard-user-card-wrapper col-md-8">
    <div class="dashboard-user-img-card col-xs-12 col-sm-6">
      <%= image_tag current_user.photo, class: "dashboard-user-img img-circle center-block" %>
    </div>
    <div class="dashboard-user-info-card col-xs-12 col-sm-4">
      <h4 class="dashboard-user-text">Name: <%= current_user.name %></h4><br>
      <h4 class="dashboard-user-text">City: <%= current_user.city %></h4><br>
      <h4 class="dashboard-user-text">State: <%= current_user.state %></h4><br>
      <div class="row">
        <%= link_to "Scheduler", scheduler_path, class: "btn btn-lg btn-default btn-home dashboard-scheduler-btn" %>
      </div>
    </div>
  </div>
  <div class="row dashboard-week-card-wrapper col-md-8">
    <h4 class="dashboard-user-text">THIS WEEK'S EVENTS</h4>
    <% @presenter.current_events.each do |event| %>
      <div class="row dashboard-event-wrapper">
        <h4>
          <%= event.name %>
          <%= event.group %>
          <%= @presenter.display_local_time(event) %>
        </h4>
        <div class="description-text">
          <%= event.description %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row dashboard-history-card-wrapper col-md-8">
    <h4 class="dashboard-user-text">HISTORY OF SELECTED EVENTS</h4>
    <% @presenter.historical_events.each do |event| %>
        <div class="row dashboard-event-wrapper">
          <h4>
            <%= event.name %>
            <%= event.group %>
            <%= @presenter.display_local_time(event) %>
          </h4>
          <div class="description-text">
            <%= event.description %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/users/scheduler.html.erb
<div class="container-fluid">
  <div class="row scheduler-events-card-wrapper col-md-8">
    <h3 class="scheduler-event-text">AVAILABLE EVENTS</h3>
      <% @presenter.matching_events.each do |event| %>
        <div class="row scheduler-event-wrapper" data-event="<%=@presenter.convert_to_json(event)%>" >
          <h4>
            <%= event[:name] %>
            <%= event[:group][:name] %>
            <%= @presenter.display_local_time(event) %>
          </h4>
          <div class="description-text">
            <%= event[:description] %>
          </div>
        </div>
      <% end %>
  </div>"
  <div class="row scheduler-selected-card-wrapper col-md-8">
    <h4 class="scheduler-event-text">SELECTED EVENTS</h4>
  </div>
  <div class="row-fluid scheduler-buttons-wrapper col-md-8">
  <form>
    <button class="save-button">Save</button>
    <button class="clear-button">Clear</button>
  </form>
  </div>
</div>

app/views/welcome/home.html.erb
<div class="container-fluid">
  <div class="row home-title-wrapper">
    <div class="home-title"><strong>EatUp</strong></div>
  </div>
  <div class="home-meetup-login-wrapper">
    <%= link_to "Log In With MeetUp", "https://secure.meetup.com/oauth2/authorize?client_id=#{ENV['MEETUP_CONSUMER_KEY']}&response_type=code&redirect_uri=#{ENV['HOST']}/login&scope=basic+ageless", class: "btn btn-lg btn-default btn-home home-login-btn" %>
  </div>